{
  "conferences" : [
    {
      "confTeams" : [
        {
          "abbreviation" : "FLA",
          "prestige" : "86",
          "hexColor" : "#132389",
          "rival" : "GA",
          "headCoach" : {
            "contractLength" : "7",
            "startYear" : "2020",
            "age" : "43",
            "ratOff" : "85",
            "cumulativePrestige" : "8",
            "ratDef" : "83",
            "homeState" : "West Virginia",
            "ratPot" : "76",
            "ratTalent" : "95",
            "baselinePrestige" : "84",
            "ratDiscipline" : "54",
            "ratOvr" : "79",
            "name" : "Anu Garfunkel",
            "contractYear" : "0"
          },
          "name" : "Florida",
          "state" : "Florida"
        },
        {
          "abbreviation" : "LSU",
          "prestige" : "85",
          "hexColor" : "#431570",
          "rival" : "ALA",
          "headCoach" : {
            "contractLength" : "4",
            "startYear" : "2020",
            "age" : "57",
            "ratOff" : "95",
            "cumulativePrestige" : "23",
            "ratDef" : "94",
            "homeState" : "North Carolina",
            "ratPot" : "89",
            "ratTalent" : "95",
            "baselinePrestige" : "92",
            "ratDiscipline" : "90",
            "ratOvr" : "93",
            "name" : "Zach Linda",
            "contractYear" : "2"
          },
          "name" : "Louisiana State",
          "state" : "Louisiana"
        },
        {
          "abbreviation" : "ALA",
          "prestige" : "94",
          "hexColor" : "#EC0D26",
          "rival" : "LSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "73",
            "cumulativePrestige" : "2",
            "ratDef" : "80",
            "homeState" : "Iowa",
            "ratPot" : "68",
            "ratTalent" : "95",
            "baselinePrestige" : "95",
            "ratDiscipline" : "80",
            "ratOvr" : "82",
            "name" : "Albert Boswink",
            "contractYear" : "2"
          },
          "name" : "Alabama",
          "state" : "Alabama"
        },
        {
          "abbreviation" : "TEN",
          "prestige" : "70",
          "hexColor" : "#D2410B",
          "rival" : "KTY",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "80",
            "cumulativePrestige" : "0",
            "ratDef" : "77",
            "homeState" : "North Dakota",
            "ratPot" : "75",
            "ratTalent" : "95",
            "baselinePrestige" : "80",
            "ratDiscipline" : "73",
            "ratOvr" : "81",
            "name" : "Lamont Reiff",
            "contractYear" : "0"
          },
          "name" : "Tennessee",
          "state" : "Tennessee"
        },
        {
          "abbreviation" : "MISS",
          "prestige" : "80",
          "hexColor" : "#380806",
          "rival" : "OM",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "60",
            "ratOff" : "91",
            "cumulativePrestige" : "25",
            "ratDef" : "82",
            "homeState" : "Florida",
            "ratPot" : "93",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "90",
            "ratOvr" : "89",
            "name" : "Rocky Tougas",
            "contractYear" : "0"
          },
          "name" : "Mississippi State",
          "state" : "Mississippi"
        },
        {
          "abbreviation" : "ARK",
          "prestige" : "57",
          "hexColor" : "#B53737",
          "rival" : "TAMU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "53",
            "ratOff" : "73",
            "cumulativePrestige" : "2",
            "ratDef" : "68",
            "homeState" : "Michigan",
            "ratPot" : "64",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "57",
            "ratOvr" : "73",
            "name" : "Jordan Cocopoti",
            "contractYear" : "0"
          },
          "name" : "Arkansas",
          "state" : "Arkansas"
        },
        {
          "abbreviation" : "GA",
          "prestige" : "89",
          "hexColor" : "#BA0C2F",
          "rival" : "FLA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "39",
            "ratOff" : "76",
            "cumulativePrestige" : "13",
            "ratDef" : "77",
            "homeState" : "Florida",
            "ratPot" : "87",
            "ratTalent" : "92",
            "baselinePrestige" : "75",
            "ratDiscipline" : "56",
            "ratOvr" : "75",
            "name" : "Taylor Dengel",
            "contractYear" : "3"
          },
          "name" : "Georgia",
          "state" : "Georgia"
        },
        {
          "abbreviation" : "TAMU",
          "prestige" : "80",
          "hexColor" : "#800000",
          "rival" : "ARK",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "58",
            "cumulativePrestige" : "0",
            "ratDef" : "61",
            "homeState" : "Florida",
            "ratPot" : "51",
            "ratTalent" : "82",
            "baselinePrestige" : "51",
            "ratDiscipline" : "52",
            "ratOvr" : "63",
            "name" : "Chad Kately",
            "contractYear" : "0"
          },
          "name" : "Texas A&M",
          "state" : "Texas"
        },
        {
          "abbreviation" : "OM",
          "prestige" : "66",
          "hexColor" : "#3232FF",
          "rival" : "MISS",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "67",
            "cumulativePrestige" : "25",
            "ratDef" : "62",
            "homeState" : "Oregon",
            "ratPot" : "50",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "60",
            "ratOvr" : "71",
            "name" : "Coy Goggin",
            "contractYear" : "2"
          },
          "name" : "Ole Miss",
          "state" : "Mississippi"
        },
        {
          "abbreviation" : "KTY",
          "prestige" : "70",
          "hexColor" : "#0000FF",
          "rival" : "TEN",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "65",
            "cumulativePrestige" : "0",
            "ratDef" : "62",
            "homeState" : "Georgia",
            "ratPot" : "98",
            "ratTalent" : "94",
            "baselinePrestige" : "45",
            "ratDiscipline" : "79",
            "ratOvr" : "75",
            "name" : "Gus Mikulich",
            "contractYear" : "0"
          },
          "name" : "Kentucky",
          "state" : "Kentucky"
        }
      ],
      "confFullName" : "Southeastern ",
      "confPrestige" : "70",
      "confName" : "SEC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "MIC",
          "prestige" : "87",
          "hexColor" : "#00274C",
          "rival" : "OHI",
          "headCoach" : {
            "contractLength" : "4",
            "startYear" : "2020",
            "age" : "51",
            "ratOff" : "95",
            "cumulativePrestige" : "27",
            "ratDef" : "95",
            "homeState" : "Massachusetts",
            "ratPot" : "90",
            "ratTalent" : "95",
            "baselinePrestige" : "92",
            "ratDiscipline" : "80",
            "ratOvr" : "91",
            "name" : "Rashad Bersch",
            "contractYear" : "2"
          },
          "name" : "Michigan",
          "state" : "Michigan"
        },
        {
          "abbreviation" : "MSU",
          "prestige" : "75",
          "hexColor" : "#18453B",
          "rival" : "PSU",
          "headCoach" : {
            "contractLength" : "5",
            "startYear" : "2020",
            "age" : "50",
            "ratOff" : "90",
            "cumulativePrestige" : "25",
            "ratDef" : "88",
            "homeState" : "Alabama",
            "ratPot" : "84",
            "ratTalent" : "95",
            "baselinePrestige" : "82",
            "ratDiscipline" : "69",
            "ratOvr" : "85",
            "name" : "Rocco Panah",
            "contractYear" : "2"
          },
          "name" : "Michigan St",
          "state" : "Michigan"
        },
        {
          "abbreviation" : "OHI",
          "prestige" : "94",
          "hexColor" : "#CE0F3D",
          "rival" : "MIC",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "60",
            "ratOff" : "87",
            "cumulativePrestige" : "0",
            "ratDef" : "77",
            "homeState" : "New Hampshire",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "87",
            "ratDiscipline" : "83",
            "ratOvr" : "85",
            "name" : "Trae Corral",
            "contractYear" : "0"
          },
          "name" : "Ohio State",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "IND",
          "prestige" : "70",
          "hexColor" : "#990000",
          "rival" : "PRD",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "79",
            "cumulativePrestige" : "27",
            "ratDef" : "77",
            "homeState" : "Wyoming",
            "ratPot" : "83",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "71",
            "ratOvr" : "80",
            "name" : "Edward Larsson",
            "contractYear" : "0"
          },
          "name" : "Indiana",
          "state" : "Indiana"
        },
        {
          "abbreviation" : "PSU",
          "prestige" : "87",
          "hexColor" : "#002D62",
          "rival" : "MSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "30",
            "ratOff" : "58",
            "cumulativePrestige" : "0",
            "ratDef" : "64",
            "homeState" : "Hawaii",
            "ratPot" : "58",
            "ratTalent" : "85",
            "baselinePrestige" : "54",
            "ratDiscipline" : "45",
            "ratOvr" : "63",
            "name" : "Warren Repko",
            "contractYear" : "0"
          },
          "name" : "Penn State",
          "state" : "Pennsylvania"
        },
        {
          "abbreviation" : "MIN",
          "prestige" : "80",
          "hexColor" : "#862334",
          "rival" : "WIS",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "59",
            "ratOff" : "54",
            "cumulativePrestige" : "0",
            "ratDef" : "64",
            "homeState" : "Michigan",
            "ratPot" : "56",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "77",
            "ratOvr" : "72",
            "name" : "Frank Biscahall",
            "contractYear" : "0"
          },
          "name" : "Minnesota",
          "state" : "Minnesota"
        },
        {
          "abbreviation" : "IWA",
          "prestige" : "83",
          "hexColor" : "#FCD116",
          "rival" : "ISU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "64",
            "cumulativePrestige" : "26",
            "ratDef" : "73",
            "homeState" : "Minnesota",
            "ratPot" : "64",
            "ratTalent" : "77",
            "baselinePrestige" : "45",
            "ratDiscipline" : "90",
            "ratOvr" : "76",
            "name" : "Saul Yasutomi",
            "contractYear" : "2"
          },
          "name" : "Iowa",
          "state" : "Iowa"
        },
        {
          "abbreviation" : "PRD",
          "prestige" : "60",
          "hexColor" : "#CEB888",
          "rival" : "IND",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "55",
            "ratOff" : "63",
            "cumulativePrestige" : "0",
            "ratDef" : "75",
            "homeState" : "North Dakota",
            "ratPot" : "70",
            "ratTalent" : "92",
            "baselinePrestige" : "59",
            "ratDiscipline" : "88",
            "ratOvr" : "79",
            "name" : "Raymundo Catanzano",
            "contractYear" : "0"
          },
          "name" : "Purdue",
          "state" : "Indiana"
        },
        {
          "abbreviation" : "WIS",
          "prestige" : "86",
          "hexColor" : "#C4012F",
          "rival" : "MIN",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "57",
            "ratOff" : "80",
            "cumulativePrestige" : "0",
            "ratDef" : "77",
            "homeState" : "Iowa",
            "ratPot" : "69",
            "ratTalent" : "93",
            "baselinePrestige" : "59",
            "ratDiscipline" : "59",
            "ratOvr" : "77",
            "name" : "Cyrus Heisman",
            "contractYear" : "0"
          },
          "name" : "Wisconsin",
          "state" : "Wisconsin"
        },
        {
          "abbreviation" : "RTG",
          "prestige" : "55",
          "hexColor" : "#CC0033",
          "rival" : "SYR",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "50",
            "ratOff" : "61",
            "cumulativePrestige" : "0",
            "ratDef" : "49",
            "homeState" : "Indiana",
            "ratPot" : "75",
            "ratTalent" : "69",
            "baselinePrestige" : "47",
            "ratDiscipline" : "69",
            "ratOvr" : "62",
            "name" : "Kory Cunning",
            "contractYear" : "0"
          },
          "name" : "Rutgers",
          "state" : "New Jersey"
        }
      ],
      "confFullName" : "Big Ten",
      "confPrestige" : "64",
      "confName" : "B1G"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "CLEM",
          "prestige" : "94",
          "hexColor" : "#F56600",
          "rival" : "UVA",
          "headCoach" : {
            "contractLength" : "3",
            "startYear" : "2020",
            "age" : "37",
            "ratOff" : "83",
            "cumulativePrestige" : "27",
            "ratDef" : "84",
            "homeState" : "Arkansas",
            "ratPot" : "58",
            "ratTalent" : "95",
            "baselinePrestige" : "87",
            "ratDiscipline" : "81",
            "ratOvr" : "85",
            "name" : "Chauncey Vesely",
            "contractYear" : "0"
          },
          "name" : "Clemson",
          "state" : "South Carolina"
        },
        {
          "abbreviation" : "UNC",
          "prestige" : "74",
          "hexColor" : "#7BAFD4",
          "rival" : "DKE",
          "headCoach" : {
            "contractLength" : "3",
            "startYear" : "2020",
            "age" : "52",
            "ratOff" : "95",
            "cumulativePrestige" : "27",
            "ratDef" : "72",
            "homeState" : "Illinois",
            "ratPot" : "79",
            "ratTalent" : "95",
            "baselinePrestige" : "72",
            "ratDiscipline" : "57",
            "ratOvr" : "79",
            "name" : "Neil Ronnie",
            "contractYear" : "0"
          },
          "name" : "North Carolina",
          "state" : "North Carolina"
        },
        {
          "abbreviation" : "UVA",
          "prestige" : "83",
          "hexColor" : "#232D4B",
          "rival" : "CLEM",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "51",
            "ratOff" : "85",
            "cumulativePrestige" : "19",
            "ratDef" : "86",
            "homeState" : "Nebraska",
            "ratPot" : "70",
            "ratTalent" : "95",
            "baselinePrestige" : "90",
            "ratDiscipline" : "70",
            "ratOvr" : "84",
            "name" : "Daniel Peppin",
            "contractYear" : "0"
          },
          "name" : "Virginia",
          "state" : "Virginia"
        },
        {
          "abbreviation" : "LOU",
          "prestige" : "79",
          "hexColor" : "#C9001F",
          "rival" : "TECH",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "53",
            "ratOff" : "84",
            "cumulativePrestige" : "25",
            "ratDef" : "79",
            "homeState" : "Rhode Island",
            "ratPot" : "67",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "79",
            "ratOvr" : "84",
            "name" : "Nic Stabell",
            "contractYear" : "0"
          },
          "name" : "Louisville",
          "state" : "Kentucky"
        },
        {
          "abbreviation" : "SYR",
          "prestige" : "70",
          "hexColor" : "#D44500",
          "rival" : "PITT",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "43",
            "ratOff" : "63",
            "cumulativePrestige" : "25",
            "ratDef" : "76",
            "homeState" : "Wyoming",
            "ratPot" : "54",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "57",
            "ratOvr" : "72",
            "name" : "Talib Housden",
            "contractYear" : "0"
          },
          "name" : "Syracuse",
          "state" : "New York"
        },
        {
          "abbreviation" : "MIA",
          "prestige" : "70",
          "hexColor" : "#005030",
          "rival" : "FSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "76",
            "cumulativePrestige" : "2",
            "ratDef" : "74",
            "homeState" : "Indiana",
            "ratPot" : "56",
            "ratTalent" : "95",
            "baselinePrestige" : "45",
            "ratDiscipline" : "76",
            "ratOvr" : "80",
            "name" : "Kelvin Poock",
            "contractYear" : "5"
          },
          "name" : "Miami",
          "state" : "Florida"
        },
        {
          "abbreviation" : "FSU",
          "prestige" : "70",
          "hexColor" : "#782F40",
          "rival" : "MIA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "51",
            "ratOff" : "59",
            "cumulativePrestige" : "0",
            "ratDef" : "58",
            "homeState" : "New Hampshire",
            "ratPot" : "74",
            "ratTalent" : "58",
            "baselinePrestige" : "45",
            "ratDiscipline" : "84",
            "ratOvr" : "64",
            "name" : "Isaac Delamater",
            "contractYear" : "0"
          },
          "name" : "Florida State",
          "state" : "Florida"
        },
        {
          "abbreviation" : "PITT",
          "prestige" : "75",
          "hexColor" : "#0C2340",
          "rival" : "SYR",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "63",
            "cumulativePrestige" : "-11",
            "ratDef" : "68",
            "homeState" : "Pennsylvania",
            "ratPot" : "71",
            "ratTalent" : "92",
            "baselinePrestige" : "60",
            "ratDiscipline" : "57",
            "ratOvr" : "70",
            "name" : "Jarell Suffield",
            "contractYear" : "2"
          },
          "name" : "Pittsburgh",
          "state" : "Pennsylvania"
        },
        {
          "abbreviation" : "DKE",
          "prestige" : "60",
          "hexColor" : "#0736A4",
          "rival" : "UNC",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "58",
            "cumulativePrestige" : "-2",
            "ratDef" : "65",
            "homeState" : "Utah",
            "ratPot" : "83",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "86",
            "ratOvr" : "76",
            "name" : "Fernando Dembowski",
            "contractYear" : "5"
          },
          "name" : "Duke",
          "state" : "North Carolina"
        },
        {
          "abbreviation" : "TECH",
          "prestige" : "60",
          "hexColor" : "#B3A369",
          "rival" : "GA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "62",
            "cumulativePrestige" : "0",
            "ratDef" : "73",
            "homeState" : "Arkansas",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "57",
            "ratDiscipline" : "59",
            "ratOvr" : "72",
            "name" : "Noah Minzy",
            "contractYear" : "0"
          },
          "name" : "Georgia Tech",
          "state" : "Georgia"
        }
      ],
      "confFullName" : "Atlantic Coast",
      "confPrestige" : "61",
      "confName" : "ACC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "WVU",
          "prestige" : "75",
          "hexColor" : "#002855",
          "rival" : "ISU",
          "headCoach" : {
            "contractLength" : "7",
            "startYear" : "2020",
            "age" : "41",
            "ratOff" : "74",
            "cumulativePrestige" : "4",
            "ratDef" : "71",
            "homeState" : "South Dakota",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "80",
            "ratDiscipline" : "81",
            "ratOvr" : "80",
            "name" : "Cody Wheeler",
            "contractYear" : "0"
          },
          "name" : "West Virginia",
          "state" : "West Virginia"
        },
        {
          "abbreviation" : "TEX",
          "prestige" : "90",
          "hexColor" : "#BF5700",
          "rival" : "OKL",
          "headCoach" : {
            "contractLength" : "7",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "86",
            "cumulativePrestige" : "27",
            "ratDef" : "95",
            "homeState" : "Arkansas",
            "ratPot" : "78",
            "ratTalent" : "95",
            "baselinePrestige" : "90",
            "ratDiscipline" : "88",
            "ratOvr" : "91",
            "name" : "Xavier Ellard",
            "contractYear" : "2"
          },
          "name" : "Texas",
          "state" : "Texas"
        },
        {
          "abbreviation" : "BAY",
          "prestige" : "84",
          "hexColor" : "#1C3C34",
          "rival" : "TCU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "27",
            "ratOff" : "78",
            "cumulativePrestige" : "0",
            "ratDef" : "79",
            "homeState" : "Mississippi",
            "ratPot" : "70",
            "ratTalent" : "95",
            "baselinePrestige" : "84",
            "ratDiscipline" : "71",
            "ratOvr" : "80",
            "name" : "Tariq Bell",
            "contractYear" : "0"
          },
          "name" : "Baylor",
          "state" : "Texas"
        },
        {
          "abbreviation" : "TTU",
          "prestige" : "80",
          "hexColor" : "#CC0000",
          "rival" : "OKS",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "37",
            "ratOff" : "94",
            "cumulativePrestige" : "27",
            "ratDef" : "95",
            "homeState" : "Oklahoma",
            "ratPot" : "88",
            "ratTalent" : "95",
            "baselinePrestige" : "80",
            "ratDiscipline" : "86",
            "ratOvr" : "92",
            "name" : "Sammy Brass",
            "contractYear" : "4"
          },
          "name" : "Texas Tech",
          "state" : "Texas"
        },
        {
          "abbreviation" : "OKL",
          "prestige" : "90",
          "hexColor" : "#841617",
          "rival" : "TEX",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "39",
            "ratOff" : "88",
            "cumulativePrestige" : "0",
            "ratDef" : "95",
            "homeState" : "New Mexico",
            "ratPot" : "90",
            "ratTalent" : "95",
            "baselinePrestige" : "87",
            "ratDiscipline" : "58",
            "ratOvr" : "84",
            "name" : "Vic Montell",
            "contractYear" : "0"
          },
          "name" : "Oklahoma",
          "state" : "Oklahoma"
        },
        {
          "abbreviation" : "OKS",
          "prestige" : "80",
          "hexColor" : "#FF7300",
          "rival" : "TTU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "36",
            "ratOff" : "66",
            "cumulativePrestige" : "0",
            "ratDef" : "78",
            "homeState" : "Missouri",
            "ratPot" : "51",
            "ratTalent" : "91",
            "baselinePrestige" : "62",
            "ratDiscipline" : "84",
            "ratOvr" : "79",
            "name" : "Cole Weese",
            "contractYear" : "0"
          },
          "name" : "Oklahoma St",
          "state" : "Oklahoma"
        },
        {
          "abbreviation" : "KU",
          "prestige" : "60",
          "hexColor" : "#0051BA",
          "rival" : "KSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "54",
            "ratOff" : "74",
            "cumulativePrestige" : "2",
            "ratDef" : "64",
            "homeState" : "West Virginia",
            "ratPot" : "62",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "80",
            "ratOvr" : "78",
            "name" : "DeAndre Destephano",
            "contractYear" : "4"
          },
          "name" : "Kansas",
          "state" : "Kansas"
        },
        {
          "abbreviation" : "TCU",
          "prestige" : "65",
          "hexColor" : "#4D1979",
          "rival" : "BAY",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "44",
            "ratOff" : "58",
            "cumulativePrestige" : "0",
            "ratDef" : "77",
            "homeState" : "Minnesota",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "64",
            "ratOvr" : "73",
            "name" : "Joshua Dyner",
            "contractYear" : "0"
          },
          "name" : "Texas Christain",
          "state" : "Texas"
        },
        {
          "abbreviation" : "ISU",
          "prestige" : "70",
          "hexColor" : "#C8102E",
          "rival" : "WVU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "30",
            "ratOff" : "62",
            "cumulativePrestige" : "0",
            "ratDef" : "62",
            "homeState" : "Washington",
            "ratPot" : "88",
            "ratTalent" : "88",
            "baselinePrestige" : "49",
            "ratDiscipline" : "51",
            "ratOvr" : "65",
            "name" : "Cory Sealey",
            "contractYear" : "0"
          },
          "name" : "Iowa State",
          "state" : "Iowa"
        },
        {
          "abbreviation" : "KSU",
          "prestige" : "80",
          "hexColor" : "#512888",
          "rival" : "KU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "35",
            "ratOff" : "65",
            "cumulativePrestige" : "-2",
            "ratDef" : "77",
            "homeState" : "Utah",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "50",
            "ratDiscipline" : "69",
            "ratOvr" : "76",
            "name" : "Joseph Geringer",
            "contractYear" : "4"
          },
          "name" : "Kansas State",
          "state" : "Kansas"
        }
      ],
      "confFullName" : "Big 12",
      "confPrestige" : "69",
      "confName" : "B12"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "UCLA",
          "prestige" : "65",
          "hexColor" : "#2D68C4",
          "rival" : "USC",
          "headCoach" : {
            "contractLength" : "4",
            "startYear" : "2020",
            "age" : "52",
            "ratOff" : "95",
            "cumulativePrestige" : "27",
            "ratDef" : "93",
            "homeState" : "Georgia",
            "ratPot" : "66",
            "ratTalent" : "95",
            "baselinePrestige" : "80",
            "ratDiscipline" : "69",
            "ratOvr" : "88",
            "name" : "Jaquan Lundman",
            "contractYear" : "2"
          },
          "name" : "UCLA",
          "state" : "California"
        },
        {
          "abbreviation" : "ORE",
          "prestige" : "90",
          "hexColor" : "#FBE021",
          "rival" : "WAS",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "44",
            "ratOff" : "85",
            "cumulativePrestige" : "28",
            "ratDef" : "83",
            "homeState" : "Missouri",
            "ratPot" : "82",
            "ratTalent" : "95",
            "baselinePrestige" : "85",
            "ratDiscipline" : "90",
            "ratOvr" : "88",
            "name" : "Dru Irvan",
            "contractYear" : "0"
          },
          "name" : "Oregon",
          "state" : "Oregon"
        },
        {
          "abbreviation" : "STAN",
          "prestige" : "69",
          "hexColor" : "#8C1515",
          "rival" : "CAL",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "48",
            "ratOff" : "88",
            "cumulativePrestige" : "25",
            "ratDef" : "91",
            "homeState" : "Arkansas",
            "ratPot" : "82",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "83",
            "ratOvr" : "89",
            "name" : "Marcus Antilla",
            "contractYear" : "0"
          },
          "name" : "Stanford",
          "state" : "California"
        },
        {
          "abbreviation" : "CAL",
          "prestige" : "70",
          "hexColor" : "#C4820F",
          "rival" : "STAN",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "44",
            "ratOff" : "75",
            "cumulativePrestige" : "0",
            "ratDef" : "75",
            "homeState" : "Michigan",
            "ratPot" : "79",
            "ratTalent" : "80",
            "baselinePrestige" : "92",
            "ratDiscipline" : "83",
            "ratOvr" : "78",
            "name" : "Taylor Ahn",
            "contractYear" : "0"
          },
          "name" : "California",
          "state" : "California"
        },
        {
          "abbreviation" : "OSU",
          "prestige" : "75",
          "hexColor" : "#DC4405",
          "rival" : "ARZ",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "90",
            "cumulativePrestige" : "8",
            "ratDef" : "81",
            "homeState" : "Arizona",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "60",
            "ratOvr" : "81",
            "name" : "Wilson Rattell",
            "contractYear" : "0"
          },
          "name" : "Oregon State",
          "state" : "Oregon"
        },
        {
          "abbreviation" : "UTH",
          "prestige" : "85",
          "hexColor" : "#CC0000",
          "rival" : "COL",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "53",
            "ratOff" : "58",
            "cumulativePrestige" : "25",
            "ratDef" : "72",
            "homeState" : "California",
            "ratPot" : "83",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "79",
            "ratOvr" : "76",
            "name" : "Rory Barra",
            "contractYear" : "2"
          },
          "name" : "Utah",
          "state" : "Utah"
        },
        {
          "abbreviation" : "WAS",
          "prestige" : "87",
          "hexColor" : "#363C74",
          "rival" : "ORE",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "35",
            "ratOff" : "70",
            "cumulativePrestige" : "2",
            "ratDef" : "65",
            "homeState" : "Montana",
            "ratPot" : "94",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "88",
            "ratOvr" : "79",
            "name" : "Jaylin Robenson",
            "contractYear" : "3"
          },
          "name" : "Washington",
          "state" : "Washington"
        },
        {
          "abbreviation" : "USC",
          "prestige" : "82",
          "hexColor" : "#9D2235",
          "rival" : "UCLA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "39",
            "ratOff" : "82",
            "cumulativePrestige" : "23",
            "ratDef" : "84",
            "homeState" : "Colorado",
            "ratPot" : "69",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "62",
            "ratOvr" : "80",
            "name" : "Elliott Lor",
            "contractYear" : "5"
          },
          "name" : "Southern California",
          "state" : "California"
        },
        {
          "abbreviation" : "COL",
          "prestige" : "60",
          "hexColor" : "#000000",
          "rival" : "UTH",
          "headCoach" : {
            "contractLength" : "7",
            "startYear" : "2020",
            "age" : "47",
            "ratOff" : "62",
            "cumulativePrestige" : "25",
            "ratDef" : "59",
            "homeState" : "Colorado",
            "ratPot" : "89",
            "ratTalent" : "95",
            "baselinePrestige" : "38",
            "ratDiscipline" : "73",
            "ratOvr" : "72",
            "name" : "Franklin Vandewege",
            "contractYear" : "2"
          },
          "name" : "Colorado",
          "state" : "Colorado"
        },
        {
          "abbreviation" : "ARZ",
          "prestige" : "57",
          "hexColor" : "#AB0520",
          "rival" : "OSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "52",
            "ratOff" : "77",
            "cumulativePrestige" : "0",
            "ratDef" : "60",
            "homeState" : "Pennsylvania",
            "ratPot" : "73",
            "ratTalent" : "53",
            "baselinePrestige" : "47",
            "ratDiscipline" : "65",
            "ratOvr" : "63",
            "name" : "Bobby Warkentin",
            "contractYear" : "0"
          },
          "name" : "Arizona",
          "state" : "Arizona"
        }
      ],
      "confFullName" : "Pacific 12",
      "confPrestige" : "67",
      "confName" : "PAC12"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "BSE",
          "prestige" : "87",
          "hexColor" : "#0033A0",
          "rival" : "WYO",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "35",
            "ratOff" : "88",
            "cumulativePrestige" : "25",
            "ratDef" : "82",
            "homeState" : "Alabama",
            "ratPot" : "50",
            "ratTalent" : "93",
            "baselinePrestige" : "80",
            "ratDiscipline" : "48",
            "ratOvr" : "77",
            "name" : "Wilfred Yancik",
            "contractYear" : "4"
          },
          "name" : "Boise State",
          "state" : "Idaho"
        },
        {
          "abbreviation" : "SDSU",
          "prestige" : "83",
          "hexColor" : "#C41230",
          "rival" : "UTST",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "78",
            "cumulativePrestige" : "27",
            "ratDef" : "81",
            "homeState" : "Delaware",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "78",
            "ratOvr" : "83",
            "name" : "Lionel Blind",
            "contractYear" : "3"
          },
          "name" : "San Diego State",
          "state" : "California"
        },
        {
          "abbreviation" : "UTST",
          "prestige" : "76",
          "hexColor" : "#0F2439",
          "rival" : "SDSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "35",
            "ratOff" : "70",
            "cumulativePrestige" : "0",
            "ratDef" : "82",
            "homeState" : "New Hampshire",
            "ratPot" : "94",
            "ratTalent" : "95",
            "baselinePrestige" : "74",
            "ratDiscipline" : "77",
            "ratOvr" : "81",
            "name" : "Carlos Romberger",
            "contractYear" : "0"
          },
          "name" : "Utah State",
          "state" : "Utah"
        },
        {
          "abbreviation" : "CSU",
          "prestige" : "61",
          "hexColor" : "#006A4D",
          "rival" : "AF",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "58",
            "ratOff" : "70",
            "cumulativePrestige" : "0",
            "ratDef" : "75",
            "homeState" : "North Dakota",
            "ratPot" : "54",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "82",
            "ratOvr" : "80",
            "name" : "Jacob Kalil",
            "contractYear" : "0"
          },
          "name" : "Colorado State",
          "state" : "Colorado"
        },
        {
          "abbreviation" : "AF",
          "prestige" : "75",
          "hexColor" : "#0033A0",
          "rival" : "CSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "41",
            "ratOff" : "66",
            "cumulativePrestige" : "0",
            "ratDef" : "87",
            "homeState" : "Pennsylvania",
            "ratPot" : "62",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "90",
            "ratOvr" : "84",
            "name" : "Rashaad Vanostberg",
            "contractYear" : "4"
          },
          "name" : "Airforce",
          "state" : "Colorado"
        },
        {
          "abbreviation" : "SJU",
          "prestige" : "50",
          "hexColor" : "#FDBF5C",
          "rival" : "FRES",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "58",
            "cumulativePrestige" : "3",
            "ratDef" : "73",
            "homeState" : "Maine",
            "ratPot" : "79",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "84",
            "ratOvr" : "77",
            "name" : "Fred Matas",
            "contractYear" : "5"
          },
          "name" : "San Jose State",
          "state" : "California"
        },
        {
          "abbreviation" : "FRES",
          "prestige" : "67",
          "hexColor" : "#CC0033",
          "rival" : "SJU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "36",
            "ratOff" : "75",
            "cumulativePrestige" : "23",
            "ratDef" : "78",
            "homeState" : "New Hampshire",
            "ratPot" : "73",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "79",
            "ratOvr" : "81",
            "name" : "Sidney Brendal",
            "contractYear" : "0"
          },
          "name" : "Fresno State",
          "state" : "California"
        },
        {
          "abbreviation" : "UNLV",
          "prestige" : "49",
          "hexColor" : "#CF0A2C",
          "rival" : "NV",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "64",
            "cumulativePrestige" : "0",
            "ratDef" : "54",
            "homeState" : "Tennessee",
            "ratPot" : "95",
            "ratTalent" : "74",
            "baselinePrestige" : "45",
            "ratDiscipline" : "62",
            "ratOvr" : "63",
            "name" : "Eddie Tointon",
            "contractYear" : "0"
          },
          "name" : "UNLV",
          "state" : "Nevada"
        },
        {
          "abbreviation" : "WYO",
          "prestige" : "75",
          "hexColor" : "#FFC425",
          "rival" : "BSE",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "47",
            "ratOff" : "56",
            "cumulativePrestige" : "0",
            "ratDef" : "60",
            "homeState" : "Pennsylvania",
            "ratPot" : "57",
            "ratTalent" : "92",
            "baselinePrestige" : "52",
            "ratDiscipline" : "47",
            "ratOvr" : "63",
            "name" : "Jacob Girardeau",
            "contractYear" : "0"
          },
          "name" : "Wyoming",
          "state" : "Wyoming"
        },
        {
          "abbreviation" : "NV",
          "prestige" : "75",
          "hexColor" : "#003366",
          "rival" : "UNLV",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "30",
            "ratOff" : "64",
            "cumulativePrestige" : "0",
            "ratDef" : "68",
            "homeState" : "Nebraska",
            "ratPot" : "70",
            "ratTalent" : "70",
            "baselinePrestige" : "47",
            "ratDiscipline" : "68",
            "ratOvr" : "67",
            "name" : "Miles Klotzbach",
            "contractYear" : "0"
          },
          "name" : "Nevada",
          "state" : "Nevada"
        }
      ],
      "confFullName" : "Mountain West",
      "confPrestige" : "60",
      "confName" : "MWC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "CIN",
          "prestige" : "85",
          "hexColor" : "#E00122",
          "rival" : "TEM",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "51",
            "ratOff" : "72",
            "cumulativePrestige" : "2",
            "ratDef" : "68",
            "homeState" : "Washington",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "85",
            "ratOvr" : "80",
            "name" : "Beau Baff",
            "contractYear" : "0"
          },
          "name" : "Cincinnati",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "MEM",
          "prestige" : "86",
          "hexColor" : "#0D3182",
          "rival" : "TUL",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "53",
            "ratOff" : "72",
            "cumulativePrestige" : "25",
            "ratDef" : "76",
            "homeState" : "New Jersey",
            "ratPot" : "52",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "57",
            "ratOvr" : "75",
            "name" : "Manny Mascaro",
            "contractYear" : "0"
          },
          "name" : "Memphis",
          "state" : "Tennessee"
        },
        {
          "abbreviation" : "HOU",
          "prestige" : "67",
          "hexColor" : "#C92A39",
          "rival" : "SMU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "40",
            "ratOff" : "95",
            "cumulativePrestige" : "25",
            "ratDef" : "95",
            "homeState" : "Louisiana",
            "ratPot" : "92",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "54",
            "ratOvr" : "84",
            "name" : "Corbin McDuffie",
            "contractYear" : "4"
          },
          "name" : "Houston",
          "state" : "Texas"
        },
        {
          "abbreviation" : "UCF",
          "prestige" : "86",
          "hexColor" : "#BA9B37",
          "rival" : "USF",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "44",
            "ratOff" : "84",
            "cumulativePrestige" : "27",
            "ratDef" : "80",
            "homeState" : "North Dakota",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "52",
            "ratOvr" : "77",
            "name" : "Tommy Jebbett",
            "contractYear" : "3"
          },
          "name" : "Central Florida",
          "state" : "Florida"
        },
        {
          "abbreviation" : "SMU",
          "prestige" : "62",
          "hexColor" : "#CC0035",
          "rival" : "HOU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "33",
            "ratOff" : "59",
            "cumulativePrestige" : "3",
            "ratDef" : "64",
            "homeState" : "Indiana",
            "ratPot" : "58",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "62",
            "ratOvr" : "70",
            "name" : "Malik Furguson",
            "contractYear" : "0"
          },
          "name" : "Southern Methodist",
          "state" : "Texas"
        },
        {
          "abbreviation" : "TUL",
          "prestige" : "80",
          "hexColor" : "#005837",
          "rival" : "MEM",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "48",
            "ratOff" : "74",
            "cumulativePrestige" : "26",
            "ratDef" : "60",
            "homeState" : "Oklahoma",
            "ratPot" : "72",
            "ratTalent" : "95",
            "baselinePrestige" : "45",
            "ratDiscipline" : "81",
            "ratOvr" : "77",
            "name" : "Jonathan Crisp",
            "contractYear" : "4"
          },
          "name" : "Tulane",
          "state" : "Louisiana"
        },
        {
          "abbreviation" : "UCON",
          "prestige" : "45",
          "hexColor" : "#000EF2",
          "rival" : "NVY",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "51",
            "ratOff" : "54",
            "cumulativePrestige" : "0",
            "ratDef" : "57",
            "homeState" : "Oklahoma",
            "ratPot" : "74",
            "ratTalent" : "53",
            "baselinePrestige" : "45",
            "ratDiscipline" : "88",
            "ratOvr" : "63",
            "name" : "Richard Ramsahai",
            "contractYear" : "0"
          },
          "name" : "Connecticut",
          "state" : "Connecticut"
        },
        {
          "abbreviation" : "USF",
          "prestige" : "75",
          "hexColor" : "#006747",
          "rival" : "UCF",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "62",
            "cumulativePrestige" : "0",
            "ratDef" : "70",
            "homeState" : "Mississippi",
            "ratPot" : "53",
            "ratTalent" : "95",
            "baselinePrestige" : "59",
            "ratDiscipline" : "75",
            "ratOvr" : "75",
            "name" : "Rashad Treisch",
            "contractYear" : "0"
          },
          "name" : "South Florida",
          "state" : "Florida"
        },
        {
          "abbreviation" : "TEM",
          "prestige" : "75",
          "hexColor" : "#990033",
          "rival" : "CIN",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "40",
            "ratOff" : "56",
            "cumulativePrestige" : "-16",
            "ratDef" : "67",
            "homeState" : "Tennessee",
            "ratPot" : "81",
            "ratTalent" : "91",
            "baselinePrestige" : "60",
            "ratDiscipline" : "47",
            "ratOvr" : "65",
            "name" : "Curtis Wands",
            "contractYear" : "2"
          },
          "name" : "Temple",
          "state" : "Pennsylvania"
        },
        {
          "abbreviation" : "NVY",
          "prestige" : "75",
          "hexColor" : "#000080",
          "rival" : "UCON",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "69",
            "cumulativePrestige" : "0",
            "ratDef" : "59",
            "homeState" : "Vermont",
            "ratPot" : "91",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "52",
            "ratOvr" : "68",
            "name" : "Kurt Talkington",
            "contractYear" : "5"
          },
          "name" : "Navy",
          "state" : "Maryland"
        }
      ],
      "confFullName" : "American Athletic",
      "confPrestige" : "57",
      "confName" : "AAC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "FAU",
          "prestige" : "82",
          "hexColor" : "#003366",
          "rival" : "FIU",
          "headCoach" : {
            "contractLength" : "4",
            "startYear" : "2020",
            "age" : "43",
            "ratOff" : "74",
            "cumulativePrestige" : "25",
            "ratDef" : "93",
            "homeState" : "Kentucky",
            "ratPot" : "60",
            "ratTalent" : "95",
            "baselinePrestige" : "80",
            "ratDiscipline" : "47",
            "ratOvr" : "77",
            "name" : "Kent Henry",
            "contractYear" : "2"
          },
          "name" : "Florida Atlantic",
          "state" : "Florida"
        },
        {
          "abbreviation" : "LATH",
          "prestige" : "70",
          "hexColor" : "#003087",
          "rival" : "NTU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "56",
            "ratOff" : "77",
            "cumulativePrestige" : "2",
            "ratDef" : "65",
            "homeState" : "Wisconsin",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "53",
            "ratOvr" : "72",
            "name" : "Ronnie McOwen",
            "contractYear" : "4"
          },
          "name" : "Lousiana Tech",
          "state" : "Louisiana"
        },
        {
          "abbreviation" : "MRSH",
          "prestige" : "66",
          "hexColor" : "#00B140",
          "rival" : "CHL",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "59",
            "ratOff" : "78",
            "cumulativePrestige" : "27",
            "ratDef" : "65",
            "homeState" : "California",
            "ratPot" : "68",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "83",
            "ratOvr" : "80",
            "name" : "Joshua Dartt",
            "contractYear" : "5"
          },
          "name" : "Marshall",
          "state" : "West Virginia"
        },
        {
          "abbreviation" : "SOMS",
          "prestige" : "65",
          "hexColor" : "#FFD046",
          "rival" : "UAB",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "41",
            "ratOff" : "80",
            "cumulativePrestige" : "25",
            "ratDef" : "77",
            "homeState" : "Nevada",
            "ratPot" : "73",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "65",
            "ratOvr" : "79",
            "name" : "Roman Halim",
            "contractYear" : "0"
          },
          "name" : "Southern Miss",
          "state" : "Mississippi"
        },
        {
          "abbreviation" : "WKU",
          "prestige" : "69",
          "hexColor" : "#B01E24",
          "rival" : "RCE",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "54",
            "ratOff" : "70",
            "cumulativePrestige" : "4",
            "ratDef" : "73",
            "homeState" : "Utah",
            "ratPot" : "92",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "66",
            "ratOvr" : "76",
            "name" : "Alec Heriford",
            "contractYear" : "5"
          },
          "name" : "Western Kentucky",
          "state" : "Kentucky"
        },
        {
          "abbreviation" : "FIU",
          "prestige" : "76",
          "hexColor" : "#081E3F",
          "rival" : "FAU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "56",
            "ratOff" : "69",
            "cumulativePrestige" : "25",
            "ratDef" : "55",
            "homeState" : "Maryland",
            "ratPot" : "63",
            "ratTalent" : "95",
            "baselinePrestige" : "50",
            "ratDiscipline" : "47",
            "ratOvr" : "66",
            "name" : "JJ Proffitt",
            "contractYear" : "5"
          },
          "name" : "Florida International",
          "state" : "Florida"
        },
        {
          "abbreviation" : "CHL",
          "prestige" : "51",
          "hexColor" : "#006940",
          "rival" : "MRSH",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "57",
            "ratOff" : "85",
            "cumulativePrestige" : "23",
            "ratDef" : "76",
            "homeState" : "Maryland",
            "ratPot" : "95",
            "ratTalent" : "87",
            "baselinePrestige" : "65",
            "ratDiscipline" : "90",
            "ratOvr" : "84",
            "name" : "Raequan Annichiarico",
            "contractYear" : "2"
          },
          "name" : "Charlotte",
          "state" : "North Carolina"
        },
        {
          "abbreviation" : "RCE",
          "prestige" : "45",
          "hexColor" : "#00205B",
          "rival" : "WKU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "68",
            "cumulativePrestige" : "0",
            "ratDef" : "64",
            "homeState" : "Pennsylvania",
            "ratPot" : "78",
            "ratTalent" : "58",
            "baselinePrestige" : "45",
            "ratDiscipline" : "53",
            "ratOvr" : "60",
            "name" : "Derron Prokes",
            "contractYear" : "0"
          },
          "name" : "Rice",
          "state" : "Texas"
        },
        {
          "abbreviation" : "NTU",
          "prestige" : "76",
          "hexColor" : "#059033",
          "rival" : "LATH",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "37",
            "ratOff" : "62",
            "cumulativePrestige" : "0",
            "ratDef" : "59",
            "homeState" : "Rhode Island",
            "ratPot" : "75",
            "ratTalent" : "94",
            "baselinePrestige" : "56",
            "ratDiscipline" : "62",
            "ratOvr" : "69",
            "name" : "Ty Carrea",
            "contractYear" : "0"
          },
          "name" : "North Texas",
          "state" : "Texas"
        },
        {
          "abbreviation" : "UAB",
          "prestige" : "53",
          "hexColor" : "#edd5a6",
          "rival" : "SOMS",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "77",
            "cumulativePrestige" : "10",
            "ratDef" : "59",
            "homeState" : "New Jersey",
            "ratPot" : "92",
            "ratTalent" : "91",
            "baselinePrestige" : "55",
            "ratDiscipline" : "70",
            "ratOvr" : "74",
            "name" : "Sidney Spearman",
            "contractYear" : "5"
          },
          "name" : "Alabama Birmingham",
          "state" : "Alabama"
        }
      ],
      "confFullName" : "Conference USA",
      "confPrestige" : "60",
      "confName" : "CUSA"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "MIOH",
          "prestige" : "84",
          "hexColor" : "#B61E2E",
          "rival" : "NIU",
          "headCoach" : {
            "contractLength" : "3",
            "startYear" : "2020",
            "age" : "33",
            "ratOff" : "95",
            "cumulativePrestige" : "27",
            "ratDef" : "79",
            "homeState" : "Hawaii",
            "ratPot" : "54",
            "ratTalent" : "95",
            "baselinePrestige" : "82",
            "ratDiscipline" : "65",
            "ratOvr" : "83",
            "name" : "Billy Morguson",
            "contractYear" : "0"
          },
          "name" : "Miami Of Ohio",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "KNT",
          "prestige" : "63",
          "hexColor" : "#002664",
          "rival" : "BUFF",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "57",
            "ratOff" : "79",
            "cumulativePrestige" : "0",
            "ratDef" : "61",
            "homeState" : "Idaho",
            "ratPot" : "86",
            "ratTalent" : "95",
            "baselinePrestige" : "63",
            "ratDiscipline" : "85",
            "ratOvr" : "80",
            "name" : "Eli Machens",
            "contractYear" : "0"
          },
          "name" : "Kent State",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "WMU",
          "prestige" : "70",
          "hexColor" : "#B5A197",
          "rival" : "CMU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "35",
            "ratOff" : "72",
            "cumulativePrestige" : "0",
            "ratDef" : "66",
            "homeState" : "Massachusetts",
            "ratPot" : "73",
            "ratTalent" : "95",
            "baselinePrestige" : "63",
            "ratDiscipline" : "71",
            "ratOvr" : "76",
            "name" : "Vincent Blette",
            "contractYear" : "0"
          },
          "name" : "Western Michigan",
          "state" : "Michigan"
        },
        {
          "abbreviation" : "OH",
          "prestige" : "70",
          "hexColor" : "#00694E",
          "rival" : "BSU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "59",
            "ratOff" : "75",
            "cumulativePrestige" : "27",
            "ratDef" : "82",
            "homeState" : "North Carolina",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "90",
            "ratOvr" : "85",
            "name" : "Moises Degrazia",
            "contractYear" : "0"
          },
          "name" : "Ohio",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "NIU",
          "prestige" : "70",
          "hexColor" : "#BA0C2F",
          "rival" : "MIOH",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "91",
            "cumulativePrestige" : "23",
            "ratDef" : "75",
            "homeState" : "Colorado",
            "ratPot" : "64",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "80",
            "ratOvr" : "85",
            "name" : "Darrell Lyford",
            "contractYear" : "5"
          },
          "name" : "Northern Illinois",
          "state" : "Illinois"
        },
        {
          "abbreviation" : "AKR",
          "prestige" : "45",
          "hexColor" : "#041E42",
          "rival" : "BGU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "59",
            "ratOff" : "69",
            "cumulativePrestige" : "6",
            "ratDef" : "75",
            "homeState" : "Connecticut",
            "ratPot" : "76",
            "ratTalent" : "95",
            "baselinePrestige" : "50",
            "ratDiscipline" : "90",
            "ratOvr" : "82",
            "name" : "Shareef Youse",
            "contractYear" : "0"
          },
          "name" : "Akron",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "CMU",
          "prestige" : "73",
          "hexColor" : "#6A0032",
          "rival" : "WMU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "82",
            "cumulativePrestige" : "0",
            "ratDef" : "83",
            "homeState" : "Pennsylvania",
            "ratPot" : "76",
            "ratTalent" : "91",
            "baselinePrestige" : "69",
            "ratDiscipline" : "69",
            "ratOvr" : "81",
            "name" : "Kenneth Aronstein",
            "contractYear" : "0"
          },
          "name" : "Central Michigan",
          "state" : "Michigan"
        },
        {
          "abbreviation" : "BSU",
          "prestige" : "56",
          "hexColor" : "#BA0C2F",
          "rival" : "OH",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "36",
            "ratOff" : "61",
            "cumulativePrestige" : "0",
            "ratDef" : "52",
            "homeState" : "Washington",
            "ratPot" : "57",
            "ratTalent" : "88",
            "baselinePrestige" : "56",
            "ratDiscipline" : "72",
            "ratOvr" : "68",
            "name" : "Roger Rushworth",
            "contractYear" : "0"
          },
          "name" : "Ball State",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "BGU",
          "prestige" : "45",
          "hexColor" : "#FE5000",
          "rival" : "AKR",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "41",
            "ratOff" : "66",
            "cumulativePrestige" : "23",
            "ratDef" : "80",
            "homeState" : "Hawaii",
            "ratPot" : "75",
            "ratTalent" : "87",
            "baselinePrestige" : "50",
            "ratDiscipline" : "63",
            "ratOvr" : "74",
            "name" : "Johnnie Singharath",
            "contractYear" : "2"
          },
          "name" : "Bowling Green",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "BUFF",
          "prestige" : "70",
          "hexColor" : "#005BBB",
          "rival" : "KNT",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "36",
            "ratOff" : "67",
            "cumulativePrestige" : "0",
            "ratDef" : "68",
            "homeState" : "Oklahoma",
            "ratPot" : "73",
            "ratTalent" : "46",
            "baselinePrestige" : "45",
            "ratDiscipline" : "86",
            "ratOvr" : "66",
            "name" : "Ernest Chaffin",
            "contractYear" : "0"
          },
          "name" : "Buffalo",
          "state" : "New York"
        }
      ],
      "confFullName" : "Mid American",
      "confPrestige" : "60",
      "confName" : "MAC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "APSU",
          "prestige" : "86",
          "hexColor" : "#FFCC00",
          "rival" : "GSN",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "80",
            "cumulativePrestige" : "25",
            "ratDef" : "73",
            "homeState" : "Oregon",
            "ratPot" : "84",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "84",
            "ratOvr" : "83",
            "name" : "Jaylin Athalone",
            "contractYear" : "0"
          },
          "name" : "Appalachian State",
          "state" : "North Carolina"
        },
        {
          "abbreviation" : "ULL",
          "prestige" : "83",
          "hexColor" : "#CE181E",
          "rival" : "ARST",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "58",
            "ratOff" : "72",
            "cumulativePrestige" : "9",
            "ratDef" : "74",
            "homeState" : "South Dakota",
            "ratPot" : "93",
            "ratTalent" : "95",
            "baselinePrestige" : "75",
            "ratDiscipline" : "90",
            "ratOvr" : "82",
            "name" : "Trevon Runkle",
            "contractYear" : "2"
          },
          "name" : "Louisiana Laffayette",
          "state" : "Louisiana"
        },
        {
          "abbreviation" : "CCU",
          "prestige" : "60",
          "hexColor" : "#006F71",
          "rival" : "GSU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "83",
            "cumulativePrestige" : "28",
            "ratDef" : "76",
            "homeState" : "Connecticut",
            "ratPot" : "91",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "90",
            "ratOvr" : "86",
            "name" : "Kenneth Fleet",
            "contractYear" : "0"
          },
          "name" : "Coastal Carolina",
          "state" : "South Carolina"
        },
        {
          "abbreviation" : "GASN",
          "prestige" : "75",
          "hexColor" : "#011E41",
          "rival" : "APST",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "45",
            "ratOff" : "70",
            "cumulativePrestige" : "5",
            "ratDef" : "74",
            "homeState" : "Maine",
            "ratPot" : "69",
            "ratTalent" : "95",
            "baselinePrestige" : "60",
            "ratDiscipline" : "72",
            "ratOvr" : "77",
            "name" : "Ron Papazian",
            "contractYear" : "0"
          },
          "name" : "Georgia Southern",
          "state" : "Georgia"
        },
        {
          "abbreviation" : "ARST",
          "prestige" : "64",
          "hexColor" : "#CC092F",
          "rival" : "ULL",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "75",
            "cumulativePrestige" : "23",
            "ratDef" : "73",
            "homeState" : "Florida",
            "ratPot" : "50",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "76",
            "ratOvr" : "79",
            "name" : "Charles Serravalli",
            "contractYear" : "4"
          },
          "name" : "Arkansas State",
          "state" : "Arkansas"
        },
        {
          "abbreviation" : "USA",
          "prestige" : "45",
          "hexColor" : "#00205B",
          "rival" : "TRY",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "30",
            "ratOff" : "55",
            "cumulativePrestige" : "0",
            "ratDef" : "56",
            "homeState" : "Vermont",
            "ratPot" : "79",
            "ratTalent" : "75",
            "baselinePrestige" : "45",
            "ratDiscipline" : "57",
            "ratOvr" : "60",
            "name" : "JaVonte Gibbs",
            "contractYear" : "0"
          },
          "name" : "South Alabama",
          "state" : "Alabama"
        },
        {
          "abbreviation" : "TRY",
          "prestige" : "66",
          "hexColor" : "#6D0017",
          "rival" : "USA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "68",
            "cumulativePrestige" : "0",
            "ratDef" : "69",
            "homeState" : "Virginia",
            "ratPot" : "95",
            "ratTalent" : "94",
            "baselinePrestige" : "58",
            "ratDiscipline" : "54",
            "ratOvr" : "71",
            "name" : "Cary Munir",
            "contractYear" : "0"
          },
          "name" : "Troy",
          "state" : "Alabama"
        },
        {
          "abbreviation" : "GSU",
          "prestige" : "60",
          "hexColor" : "#0039A6",
          "rival" : "USA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "67",
            "cumulativePrestige" : "0",
            "ratDef" : "64",
            "homeState" : "South Carolina",
            "ratPot" : "91",
            "ratTalent" : "69",
            "baselinePrestige" : "52",
            "ratDiscipline" : "54",
            "ratOvr" : "63",
            "name" : "Brandon Casilles",
            "contractYear" : "0"
          },
          "name" : "Georgia State",
          "state" : "Georgia"
        },
        {
          "abbreviation" : "TSU",
          "prestige" : "52",
          "hexColor" : "#501214",
          "rival" : "ULM",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "33",
            "ratOff" : "61",
            "cumulativePrestige" : "0",
            "ratDef" : "51",
            "homeState" : "Arkansas",
            "ratPot" : "79",
            "ratTalent" : "56",
            "baselinePrestige" : "52",
            "ratDiscipline" : "72",
            "ratOvr" : "60",
            "name" : "Tim Wachsmuth",
            "contractYear" : "0"
          },
          "name" : "Texas State",
          "state" : "Texas"
        },
        {
          "abbreviation" : "ULM",
          "prestige" : "60",
          "hexColor" : "#800029",
          "rival" : "TSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "34",
            "ratOff" : "65",
            "cumulativePrestige" : "0",
            "ratDef" : "70",
            "homeState" : "Alabama",
            "ratPot" : "78",
            "ratTalent" : "95",
            "baselinePrestige" : "54",
            "ratDiscipline" : "52",
            "ratOvr" : "70",
            "name" : "Reid Hirshberg",
            "contractYear" : "0"
          },
          "name" : "Louisiana Monroe",
          "state" : "Louisiana"
        }
      ],
      "confFullName" : "Sun Belt",
      "confPrestige" : "57",
      "confName" : "SNBLT"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "INST",
          "prestige" : "63",
          "hexColor" : "#0142BC",
          "rival" : "MIST",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "54",
            "ratOff" : "83",
            "cumulativePrestige" : "27",
            "ratDef" : "79",
            "homeState" : "Louisiana",
            "ratPot" : "85",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "85",
            "ratOvr" : "85",
            "name" : "Kevin Turbide",
            "contractYear" : "0"
          },
          "name" : "Indiana State",
          "state" : "Indiana"
        },
        {
          "abbreviation" : "NDSU",
          "prestige" : "87",
          "hexColor" : "#005644",
          "rival" : "SDST",
          "headCoach" : {
            "contractLength" : "4",
            "startYear" : "2020",
            "age" : "50",
            "ratOff" : "92",
            "cumulativePrestige" : "27",
            "ratDef" : "95",
            "homeState" : "Ohio",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "67",
            "ratDiscipline" : "53",
            "ratOvr" : "83",
            "name" : "Reggie Dito",
            "contractYear" : "2"
          },
          "name" : "North Dakota State",
          "state" : "North Dakota"
        },
        {
          "abbreviation" : "NOIA",
          "prestige" : "74",
          "hexColor" : "#4B116F",
          "rival" : "SD",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "57",
            "ratOff" : "92",
            "cumulativePrestige" : "23",
            "ratDef" : "95",
            "homeState" : "South Carolina",
            "ratPot" : "95",
            "ratTalent" : "95",
            "baselinePrestige" : "70",
            "ratDiscipline" : "85",
            "ratOvr" : "91",
            "name" : "Chris Thomas",
            "contractYear" : "3"
          },
          "name" : "Northern Iowa",
          "state" : "Iowa"
        },
        {
          "abbreviation" : "ILST",
          "prestige" : "75",
          "hexColor" : "#CE1126",
          "rival" : "SIU",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "52",
            "ratOff" : "71",
            "cumulativePrestige" : "2",
            "ratDef" : "71",
            "homeState" : "Delaware",
            "ratPot" : "58",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "59",
            "ratOvr" : "74",
            "name" : "Bernard Famiglietti",
            "contractYear" : "0"
          },
          "name" : "Illinois State",
          "state" : "Illinois"
        },
        {
          "abbreviation" : "YSU",
          "prestige" : "45",
          "hexColor" : "#C8102E",
          "rival" : "WIU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "40",
            "ratOff" : "63",
            "cumulativePrestige" : "0",
            "ratDef" : "55",
            "homeState" : "Maryland",
            "ratPot" : "65",
            "ratTalent" : "68",
            "baselinePrestige" : "45",
            "ratDiscipline" : "69",
            "ratOvr" : "63",
            "name" : "Omarr Grumney",
            "contractYear" : "0"
          },
          "name" : "Youngston State",
          "state" : "Ohio"
        },
        {
          "abbreviation" : "SIU",
          "prestige" : "70",
          "hexColor" : "#720000",
          "rival" : "ILST",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "36",
            "ratOff" : "70",
            "cumulativePrestige" : "0",
            "ratDef" : "66",
            "homeState" : "Maryland",
            "ratPot" : "91",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "68",
            "ratOvr" : "74",
            "name" : "Trevon Mayard",
            "contractYear" : "4"
          },
          "name" : "Southern Illinois",
          "state" : "Illinois"
        },
        {
          "abbreviation" : "SDST",
          "prestige" : "80",
          "hexColor" : "#0032A0",
          "rival" : "NDSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "43",
            "ratOff" : "64",
            "cumulativePrestige" : "-2",
            "ratDef" : "74",
            "homeState" : "Nevada",
            "ratPot" : "86",
            "ratTalent" : "95",
            "baselinePrestige" : "60",
            "ratDiscipline" : "87",
            "ratOvr" : "80",
            "name" : "Tyrone Alm",
            "contractYear" : "3"
          },
          "name" : "South Dakota State",
          "state" : "South Dakota"
        },
        {
          "abbreviation" : "SD",
          "prestige" : "66",
          "hexColor" : "#AD0000",
          "rival" : "NOIA",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "57",
            "ratOff" : "64",
            "cumulativePrestige" : "0",
            "ratDef" : "67",
            "homeState" : "Arizona",
            "ratPot" : "86",
            "ratTalent" : "95",
            "baselinePrestige" : "57",
            "ratDiscipline" : "78",
            "ratOvr" : "76",
            "name" : "Bryan Ibanez",
            "contractYear" : "0"
          },
          "name" : "South Dakota",
          "state" : "South Dakota"
        },
        {
          "abbreviation" : "WIU",
          "prestige" : "56",
          "hexColor" : "#663399",
          "rival" : "YSU",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "49",
            "ratOff" : "60",
            "cumulativePrestige" : "0",
            "ratDef" : "62",
            "homeState" : "Iowa",
            "ratPot" : "66",
            "ratTalent" : "92",
            "baselinePrestige" : "56",
            "ratDiscipline" : "84",
            "ratOvr" : "74",
            "name" : "Eli Urquilla",
            "contractYear" : "0"
          },
          "name" : "Western Illinois",
          "state" : "Illinois"
        },
        {
          "abbreviation" : "MIST",
          "prestige" : "75",
          "hexColor" : "#5E0009",
          "rival" : "INST",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "57",
            "cumulativePrestige" : "0",
            "ratDef" : "64",
            "homeState" : "West Virginia",
            "ratPot" : "53",
            "ratTalent" : "79",
            "baselinePrestige" : "48",
            "ratDiscipline" : "51",
            "ratOvr" : "62",
            "name" : "Kevin Tallman",
            "contractYear" : "0"
          },
          "name" : "Missouri State",
          "state" : "Missouri"
        }
      ],
      "confFullName" : "Missouri Valley",
      "confPrestige" : "56",
      "confName" : "MVC"
    },
    {
      "confTeams" : [
        {
          "abbreviation" : "NMST",
          "prestige" : "45",
          "hexColor" : "#FF0030",
          "rival" : "MRMK",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "37",
            "ratOff" : "69",
            "cumulativePrestige" : "0",
            "ratDef" : "51",
            "homeState" : "Idaho",
            "ratPot" : "97",
            "ratTalent" : "88",
            "baselinePrestige" : "45",
            "ratDiscipline" : "62",
            "ratOvr" : "67",
            "name" : "Shawn Kipling",
            "contractYear" : "0"
          },
          "name" : "New Mexico State",
          "state" : "New Mexico"
        },
        {
          "abbreviation" : "ND",
          "prestige" : "90",
          "hexColor" : "#0C2340",
          "rival" : "NRDK",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "44",
            "ratOff" : "89",
            "cumulativePrestige" : "27",
            "ratDef" : "90",
            "homeState" : "West Virginia",
            "ratPot" : "51",
            "ratTalent" : "95",
            "baselinePrestige" : "60",
            "ratDiscipline" : "80",
            "ratOvr" : "88",
            "name" : "Brent Monopoli",
            "contractYear" : "4"
          },
          "name" : "Notre Dame",
          "state" : "Indiana"
        },
        {
          "abbreviation" : "BYU",
          "prestige" : "70",
          "hexColor" : "#002E5D",
          "rival" : "NMST",
          "headCoach" : {
            "contractLength" : "2",
            "startYear" : "2020",
            "age" : "36",
            "ratOff" : "75",
            "cumulativePrestige" : "25",
            "ratDef" : "84",
            "homeState" : "Rhode Island",
            "ratPot" : "65",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "47",
            "ratOvr" : "75",
            "name" : "Jason Spana",
            "contractYear" : "0"
          },
          "name" : "Brigham Young",
          "state" : "Utah"
        },
        {
          "abbreviation" : "MRMK",
          "prestige" : "48",
          "hexColor" : "#0B335E",
          "rival" : "LBY",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "42",
            "ratOff" : "69",
            "cumulativePrestige" : "2",
            "ratDef" : "68",
            "homeState" : "Rhode Island",
            "ratPot" : "61",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "56",
            "ratOvr" : "72",
            "name" : "Clay Muffoletto",
            "contractYear" : "2"
          },
          "name" : "Merrimack",
          "state" : "Massachusetts"
        },
        {
          "abbreviation" : "HRV",
          "prestige" : "55",
          "hexColor" : "#090016",
          "rival" : "YLE",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "54",
            "ratOff" : "59",
            "cumulativePrestige" : "23",
            "ratDef" : "73",
            "homeState" : "Alabama",
            "ratPot" : "69",
            "ratTalent" : "95",
            "baselinePrestige" : "65",
            "ratDiscipline" : "72",
            "ratOvr" : "74",
            "name" : "Anthony Gelfand",
            "contractYear" : "2"
          },
          "name" : "Harvard",
          "state" : "Massachusetts"
        },
        {
          "abbreviation" : "AMY",
          "prestige" : "70",
          "hexColor" : "#000000",
          "rival" : "UMAS",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "39",
            "ratOff" : "69",
            "cumulativePrestige" : "11",
            "ratDef" : "60",
            "homeState" : "Kansas",
            "ratPot" : "68",
            "ratTalent" : "91",
            "baselinePrestige" : "70",
            "ratDiscipline" : "73",
            "ratOvr" : "73",
            "name" : "Darryl An",
            "contractYear" : "4"
          },
          "name" : "Army",
          "state" : "New York"
        },
        {
          "abbreviation" : "YLE",
          "prestige" : "56",
          "hexColor" : "#0F4D92",
          "rival" : "HRV",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "38",
            "ratOff" : "68",
            "cumulativePrestige" : "30",
            "ratDef" : "87",
            "homeState" : "South Carolina",
            "ratPot" : "87",
            "ratTalent" : "95",
            "baselinePrestige" : "50",
            "ratDiscipline" : "87",
            "ratOvr" : "84",
            "name" : "Raymond Saracco",
            "contractYear" : "4"
          },
          "name" : "Yale",
          "state" : "Connecticut"
        },
        {
          "abbreviation" : "NRDK",
          "prestige" : "79",
          "hexColor" : "#009A44",
          "rival" : "ND",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "47",
            "ratOff" : "46",
            "cumulativePrestige" : "0",
            "ratDef" : "61",
            "homeState" : "West Virginia",
            "ratPot" : "84",
            "ratTalent" : "78",
            "baselinePrestige" : "45",
            "ratDiscipline" : "68",
            "ratOvr" : "63",
            "name" : "Davis Rieg",
            "contractYear" : "0"
          },
          "name" : "North Dakota",
          "state" : "North Dakota"
        },
        {
          "abbreviation" : "LBY",
          "prestige" : "62",
          "hexColor" : "#0A254E",
          "rival" : "MRMK",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "41",
            "ratOff" : "66",
            "cumulativePrestige" : "8",
            "ratDef" : "67",
            "homeState" : "Nevada",
            "ratPot" : "93",
            "ratTalent" : "91",
            "baselinePrestige" : "65",
            "ratDiscipline" : "90",
            "ratOvr" : "78",
            "name" : "Chuck Hullum",
            "contractYear" : "3"
          },
          "name" : "Liberty",
          "state" : "Virginia"
        },
        {
          "abbreviation" : "UMAS",
          "prestige" : "45",
          "hexColor" : "#971B2F",
          "rival" : "AMY",
          "headCoach" : {
            "contractLength" : "6",
            "startYear" : "2020",
            "age" : "60",
            "ratOff" : "70",
            "cumulativePrestige" : "0",
            "ratDef" : "73",
            "homeState" : "Alaska",
            "ratPot" : "77",
            "ratTalent" : "95",
            "baselinePrestige" : "55",
            "ratDiscipline" : "84",
            "ratOvr" : "80",
            "name" : "Wade Fowles",
            "contractYear" : "5"
          },
          "name" : "Massachusetts",
          "state" : "Massachusetts"
        }
      ],
      "confFullName" : "Independents",
      "confPrestige" : "54",
      "confName" : "IND"
    }
  ],
  "bowlGames" : [
    "Rose Bowl",
    "Fiesta Bowl",
    "Peach Bowl",
    "Sugar Bowl",
    "Citrus Bowl",
    "Cotton Bowl",
    "Orange Bowl",
    "Outback Bowl",
    "Liberty Bowl",
    "Music City Bowl",
    "Gator Bowl",
    "Birmingham Bowl",
    "Independence Bowl",
    "Camping World Bowl",
    "Holiday Bowl",
    "Famous Idaho Potato Bowl",
    "Insight Bowl",
    "Alamo Bowl",
    "Tropical Bowl",
    "Music Bowl",
    "New Orleans Bowl",
    "Belk Bowl",
    "Lending Tree Bowl",
    "Red Box Bowl",
    "Hawaii Bowl",
    "Armed Forces Bowl",
    "Las Vegas Bowl",
    "Mortgage Cure Bowl",
    "Texas Bowl",
    "Bahamas Bowl",
    "Celebration Bowl",
    "Cheez-It Bowl",
    "Boca Raton Bowl",
    "Fenway Bowl",
    "LA Bowl",
    "Arizona Bowl"
  ]
}
